#!/usr/bin/env bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Summary: make it easy to run pylint on directories that contain Python files
# and avoid tests/googletest/.

set -e

declare -r usage="Usage: ${0} [-h | --help] [args ...]

If the first argument on the command line is the option --help or -h, this
program prints usage information and then exits. Otherwise, it runs Pylint on
the Python files of this project. It passes all command-line arguments (other
than -h, --help, or help) to Pylint along with the project source directories."

# Exit early if the user requested help.
if [[ "${1}" == "-h" || "${1}" == "--help" || "${1}" == "help" ]]; then
    echo "$usage"
    exit 0
fi

# Go to the project root.
thisdir=$(dirname "${BASH_SOURCE[0]:?}")
repo_dir=$(git -C "${thisdir}" rev-parse --show-toplevel)
cd "${repo_dir}"

pylint --jobs=0 --recursive=y --ignore-paths=tests/googletest "$@" .
