name: Question
description: As a question
type: Question
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for your interest in qsim! Before continuing, it's worth
        [searching through the existing issues in this
        repository](https://github.com/quantumlib/qsim/issues?q=is%3Aissue) in
        case the same question has already been asked and possibly answered.

  - type: textarea
    attributes:
      label: What is the question?
      description: >-
        Please provide enough details and contextual information so that the
        question is answerable.
      placeholder: >-
        Write your question here
    validations:
      required: true

  - type: input
    attributes:
      label: Does this concern a specific version of qsim? If so, what version?
      placeholder: >-
        Write the qsim version number here
    validations:
      required: false

  - type: input
    attributes:
      label: Is it specific to a computing environment? If so, which one?
      description: >-
        If the platform and operating system version may be relevant, please
        tell us those details as well. It may matter, for example, whether you
        are using Linux, macOS, Windows, or Google Colab, as well as whether
        you are trying to use CUDA (and what version), and other details.
      placeholder: >-
        Describe the computing environment here
    validations:
      required: false
