universe                = docker
docker_image            = gcr.io/quantum-builds/github.com/quantumlib/qsim
arguments               = -c circuit_q30
transfer_input_files    = ../../../circuits/circuit_q30
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = out/out.$(Cluster)-$(Process)
error                   = out/err.$(Cluster)-$(Process)
log                     = out/log.$(Cluster)-$(Process)
request_memory          = 10GB
queue 1
