# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Repository rule to probe compiler support and host CPU features."""

def _is_windows(os_name):
    return "windows" in os_name

def _is_macos(os_name):
    return "mac" in os_name or "darwin" in os_name

def _compiler_probe_impl(repo_ctx):
    os_name = repo_ctx.os.name.lower()
    is_win = _is_windows(os_name)
    is_mac = _is_macos(os_name)

    default_cc = "cl.exe" if is_win else "c++"
    env_cc = repo_ctx.os.environ.get("CC", default_cc)
    cc_path = repo_ctx.which(env_cc)
    cc = str(cc_path) if cc_path else env_cc

    supports_gsframe = False
    cpu_info = ""

    if is_mac:
        result = repo_ctx.execute([
            "sysctl",
            "-n",
            "machdep.cpu.features",
            "machdep.cpu.leaf7_features",
        ])
        cpu_info = result.stdout if result.return_code == 0 else ""
    elif not is_win:
        result = repo_ctx.execute(["cat", "/proc/cpuinfo"])
        cpu_info = result.stdout if result.return_code == 0 else ""

    # Run a test compilation to test if the SFrame flag is recognized.
    if not is_win:
        gsframe_test = repo_ctx.execute([
            cc,
            "-Wa,--gsframe=no",
            "-c",
            "-x",
            "c++",
            "/dev/null",
            "-o",
            "/dev/null",
        ])
        supports_gsframe = (gsframe_test.return_code == 0)

    features = get_cpu_features(os_name, cpu_info)
    avx_copts, sse_copts = get_compiler_flags(os_name, features)

    repo_ctx.file(
        "BUILD.bazel",
        "package(default_visibility = ['//visibility:public'])\n",
    )
    repo_ctx.file(
        "compiler_config.bzl",
        """# Generated by compiler_probe.bzl. Do not edit.
SUPPORTS_GSFRAME = {gsframe}
AVX_COPTS = {avx}
SSE_COPTS = {sse}
""".format(
            gsframe = supports_gsframe,
            avx = avx_copts,
            sse = sse_copts,
        ),
    )

def get_cpu_features(os_name, cpu_info):
    """Parses system command output to identify CPU features.

    Args:
        os_name: The lowercase name of the OS (from repository_ctx.os.name).
        cpu_info: String containing CPU feature flags.

    Returns:
        A dict of detected features.
    """

    # Protection against None/empty command execution outputs.
    cpu_info_lower = (cpu_info or "").lower()
    is_win = _is_windows(os_name)

    # Map desired feature keys to strings we expect to find in the OS output.
    feature_map = {
        "avx512f": ["avx512f"],
        "avx2": ["avx2"],
        "fma": ["fma"],
        "bmi2": ["bmi2"],
        "sse4": ["sse4_1", "sse4_2", "sse4.1", "sse4.2"],
        "sse2": ["sse2"],
    }

    features = {}
    for feat, search_terms in feature_map.items():
        if is_win:
            # Heuristic fallback for Windows hosts.
            features[feat] = feat in ("avx2", "sse4", "sse2")
        else:
            features[feat] = any([term in cpu_info_lower for term in search_terms])

    return features

def get_compiler_flags(os_name, features):
    """Determines compiler flags based on OS and detected features.

    Args:
        os_name: The lowercase name of the OS.
        features: A dict of detected features (from get_cpu_features).

    Returns:
        A tuple of (avx_copts, sse_copts).
    """
    is_win = _is_windows(os_name)
    avx_copts = []
    sse_copts = []

    if is_win:
        if features.get("avx512f"):
            avx_copts = ["/arch:AVX512"]
        elif features.get("avx2"):
            avx_copts = ["/arch:AVX2"]
        else:
            avx_copts = ["/arch:AVX"]
    else:
        if features.get("avx512f"):
            avx_copts = ["-mavx512f", "-mbmi2"]
        elif features.get("avx2"):
            avx_copts = ["-mavx2", "-mfma"] + (["-mbmi2"] if features.get("bmi2") else [])
        else:
            avx_copts = ["-mavx"]

        if features.get("sse4"):
            sse_copts = ["-msse4"]
        elif features.get("sse2"):
            sse_copts = ["-msse2"]

    return avx_copts, sse_copts

compiler_probe = repository_rule(
    implementation = _compiler_probe_impl,
    local = True,
    environ = ["CC", "PATH"],
)
