# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Repository rule to probe compiler support and host CPU features."""

def _is_windows(os_name):
    return "windows" in os_name

def _is_macos(os_name):
    return "mac" in os_name or "darwin" in os_name

def _compiler_probe_impl(repo_ctx):
    os_name = repo_ctx.os.name.lower()
    is_win = _is_windows(os_name)
    is_mac = _is_macos(os_name)

    default_cc = "cl.exe" if is_win else "c++"
    env_cc = repo_ctx.os.environ.get("CC", default_cc)
    cc_path = repo_ctx.which(env_cc)
    cc = str(cc_path) if cc_path else env_cc

    supports_gsframe = False
    cpu_info = ""

    if is_mac:
        result = repo_ctx.execute([
            "sysctl",
            "-n",
            "machdep.cpu.features",
            "machdep.cpu.leaf7_features",
        ])
        cpu_info = result.stdout if result.return_code == 0 else ""
    elif not is_win:
        result = repo_ctx.execute(["cat", "/proc/cpuinfo"])
        cpu_info = result.stdout if result.return_code == 0 else ""

    # Run a test compilation to test if the SFrame flag is recognized.
    if not is_win:
        gsframe_test = repo_ctx.execute([
            cc,
            "-Wa,--gsframe=no",
            "-c",
            "-x",
            "c++",
            "/dev/null",
            "-o",
            "/dev/null",
        ])
        supports_gsframe = (gsframe_test.return_code == 0)

    features = get_cpu_features(os_name, cpu_info)
    avx_copts, sse_copts = get_compiler_flags(os_name, features)
    has_avx, has_avx2, has_avx512, has_sse, has_bmi, has_bmi2, cpu_features_str = get_feature_booleans(features)

    # Specific flags for requested levels
    if is_win:
        avx2_flags = ["/arch:AVX2"]
        avx512_flags = ["/arch:AVX512"]
    else:
        avx2_flags = ["-mavx2", "-mfma"]
        avx512_flags = ["-mavx512f", "-mavx2", "-mfma"]

    bmi_flags = ["-mbmi"] if has_bmi and not has_bmi2 else []
    bmi2_flags = ["-mbmi2"] if has_bmi2 else []

    repo_ctx.file(
        "BUILD.bazel",
        "package(default_visibility = ['//visibility:public'])\n",
    )
    repo_ctx.file(
        "compiler_config.bzl",
        """# Generated by compiler_probe.bzl. Do not edit.
SUPPORTS_GSFRAME = {gsframe}
AVX_COPTS = {avx}
AVX2_COPTS = {avx2}
AVX512_COPTS = {avx512}
SSE_COPTS = {sse}
BMI_COPTS = {bmi}
BMI2_COPTS = {bmi2}
CPU_FEATURES_STR = "{cpu_features}"
HOST_HAS_AVX = {has_avx}
HOST_HAS_AVX2 = {has_avx2}
HOST_HAS_AVX512 = {has_avx512}
HOST_HAS_SSE = {has_sse}
HOST_HAS_BMI = {has_bmi}
HOST_HAS_BMI2 = {has_bmi2}
""".format(
            gsframe = supports_gsframe,
            avx = avx_copts,
            avx2 = avx2_flags,
            avx512 = avx512_flags,
            sse = sse_copts,
            bmi = bmi_flags,
            bmi2 = bmi2_flags,
            cpu_features = cpu_features_str,
            has_avx = has_avx,
            has_avx2 = has_avx2,
            has_avx512 = has_avx512,
            has_sse = has_sse,
            has_bmi = has_bmi,
            has_bmi2 = has_bmi2,
        ),
    )

    # Print a message to inform the user what was found.
    flags_str = " ".join(avx_copts) + " " + " ".join(sse_copts) + " " + " ".join(bmi_flags) + " " + " ".join(bmi2_flags)
    print("Host CPU features detected: " + cpu_features_str)  # buildifier: disable=print
    print("Available host-optimized flags: " + flags_str)  # buildifier: disable=print

def get_feature_booleans(features):
    """Summarizes feature presence as booleans and a string.

    Args:
        features: A dict of detected features (from get_cpu_features).

    Returns:
        A tuple of (has_avx, has_avx2, has_avx512, has_sse, has_bmi, has_bmi2, cpu_features_str).
    """
    cpu_features_str = " ".join([feat.upper() for feat, found in features.items() if found])
    has_avx = features.get("avx", False)
    has_avx2 = features.get("avx2", False)
    has_avx512 = features.get("avx512f", False)
    has_sse = "SSE" in cpu_features_str
    has_bmi = features.get("bmi", False)
    has_bmi2 = features.get("bmi2", False)
    return has_avx, has_avx2, has_avx512, has_sse, has_bmi, has_bmi2, cpu_features_str

def get_cpu_features(os_name, cpu_info):
    """Parses system command output to identify CPU features.

    Args:
        os_name: The lowercase name of the OS (from repository_ctx.os.name).
        cpu_info: String containing CPU feature flags.

    Returns:
        A dict of detected features.
    """

    # Protection against None/empty command execution outputs.
    cpu_info_lower = (cpu_info or "").lower()
    is_win = _is_windows(os_name)

    # Map desired feature keys to strings we expect to find in the OS output.
    feature_map = {
        "avx512f": ["avx512f"],
        "avx2": ["avx2"],
        "avx": ["avx"],
        "fma": ["fma"],
        "bmi": ["bmi1", "bmi "],  # bmi1 is often just 'bmi'
        "bmi2": ["bmi2"],
        "sse4": ["sse4_1", "sse4_2", "sse4.1", "sse4.2"],
        "sse2": ["sse2"],
    }

    features = {}
    for feat, search_terms in feature_map.items():
        if is_win:
            # Heuristic fallback for Windows hosts.
            features[feat] = feat in ("avx", "avx2", "sse4", "sse2")
        else:
            features[feat] = any([term in cpu_info_lower for term in search_terms])

    return features

def get_compiler_flags(os_name, features):
    """Determines compiler flags based on OS and detected features.

    Args:
        os_name: The lowercase name of the OS.
        features: A dict of detected features (from get_cpu_features).

    Returns:
        A tuple of (avx_copts, sse_copts).
    """
    is_win = _is_windows(os_name)
    avx_copts = []
    sse_copts = []

    if is_win:
        if features.get("avx512f"):
            avx_copts = ["/arch:AVX512"]
        elif features.get("avx2"):
            avx_copts = ["/arch:AVX2"]
        else:
            avx_copts = ["/arch:AVX"]
    else:
        if features.get("avx512f"):
            avx_copts = ["-mavx512f"]
        elif features.get("avx2"):
            avx_copts = ["-mavx2", "-mfma"]
        else:
            avx_copts = ["-mavx"]

        if features.get("sse4"):
            sse_copts = ["-msse4"]
        elif features.get("sse2"):
            sse_copts = ["-msse2"]

    return avx_copts, sse_copts

compiler_probe = repository_rule(
    implementation = _compiler_probe_impl,
    local = True,
    environ = ["CC", "PATH"],
)
