# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CI: build & test Docker images'
run-name: Build Docker images and test them

on:
  push:
    branches:
      - master
      - main

  pull_request:
    types: [opened, synchronize]

  merge_group:
    types:
      - checks_requested

  workflow_dispatch:
    inputs:
      debug:
        description: 'Run with debugging options'
        type: boolean
        default: true

permissions: read-all

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  find-changes:
    name: Find changed files
    uses: ./.github/workflows/_find_changes.yaml
    secrets: inherit

  run-tests:
    if: ${{needs.find-changes.outputs.code == 'true' || inputs.debug}}
    name: Run tests
    needs: find-changes
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    env:
      # The next environment variable is used by Docker.
      BUILDKIT_PROGRESS: ${{inputs.debug && 'plain' || ''}}
    steps:
      - if: >-
          ${{needs.find-changes.outputs.code == 'false'
            && github.event_name != 'workflow_dispatch'}}
        name: Exit early if there were no changes to code files
        run: exit 0

      - name: Check out a copy of the git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Build Docker images
        run: |
          # Running locally, a plain "docker compose build" works as expected.
          # On GitHub, buildx tries to build all 3 images in parallel even if
          # you set COMPOSE_PARALLEL_LIMIT or use --parallel 1. That fails b/c
          # the qsim-base image is not available to the other two build jobs.
          docker compose build qsim-base-image
          docker compose build qsim-cxx-tests-image qsim-py-tests-image

      - name: Run C++ tests
        run: docker run --rm qsim-cxx-tests:latest

      - name: Run Python tests
        run: docker run --rm qsim-py-tests:latest

      - name: Run a sample simulation
        run: docker run --rm qsim-base:latest -c /qsim/circuits/circuit_q24

      - name: Test installation process
        run: |
          cd install/tests
          docker compose build

  report-results:
    if: always()
    name: ${{github.workflow}}
    needs: run-tests
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Exit with an appropriate status code
        run: |
          result="${{needs.run-tests.result}}"
          [[ "$result" == "success" || "$result" == "skipped" ]]
